### ISSUE TITLE
wrong typescript definition for getBlockByNumber

### ISSUE THREAD

**Issue by bajpai244** [NilFoundation/nil.js#90]
[Here](https://github.com/NilFoundation/nil.js/blob/0a7cfa0a78af03b5a962d801090f070a4c5a3e80/src/clients/PublicClient.ts#L100), the type for `blockNumber` is `Hex`, but it should actually be `Hex | BlockTag`

Where BlockTag should be an enum of correct block tags as per eth RPC specification.

I am currently travelling this weekend, but I can take this on Monday, but if someone wants to solve in between then feel free to as well!

**Comment by ukorvl** [comment]
Done in v0.16.0
